### ISSUE TITLE
NoClassDefFoundError: TextFlowLayout

### ISSUE THREAD

**Issue by kuzmenkoGift** [FXMisc/RichTextFX#829]
## NoClassDefFoundError after updating to 0.10.1

I was using class InlineCssTextArea from your library. 
Previously i was using version 0.9.3  and it worked good, but when i tried to change to version 0.10.1, i get new error: 

````
java.lang.NoClassDefFoundError: org/fxmisc/richtext/TextFlowLayout
	at org.fxmisc.richtext.TextFlowExt.textLayout(TextFlowExt.java:29) ~[richtextfx-0.10.0.jar!/:0.10.0]
	at org.fxmisc.richtext.TextFlowExt.getLineCount(TextFlowExt.java:35) ~[richtextfx-0.10.0.jar!/:0.10.0]
	at org.fxmisc.richtext.ParagraphText.getRangeShapeSafely(ParagraphText.java:377) ~[richtextfx-0.10.0.jar!/:0.10.0]
	at org.fxmisc.richtext.ParagraphText.getRangeShapeSafely(ParagraphText.java:329) ~[richtextfx-0.10.0.jar!/:0.10.0]
	at org.fxmisc.richtext.ParagraphText.updateSingleSelection(ParagraphText.java:325) ~[richtextfx-0.10.0.jar!/:0.10.0]
	at org.fxmisc.richtext.ParagraphText.lambda$new$1(ParagraphText.java:115) ~[richtextfx-0.10.0.jar!/:0.10.0]
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163) ~[javafx-base-11-linux.jar!/:na]
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72) ~[javafx-base-11-linux.jar!/:na]
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115) ~[javafx-base-11-linux.jar!/:na]
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173) ~[javafx-base-11-linux.jar!/:na]
	at org.fxmisc.richtext.GenericStyledArea.lambda$createCell$43(GenericStyledArea.java:1440) ~[richtextfx-0.10.0.jar!/:0.10.0]
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134) ~[reactfx-2.0-M5.jar!/:na]

````

To add library to project, i am using maven
````
        <dependency>
            <groupId>org.fxmisc.richtext</groupId>
            <artifactId>richtextfx</artifactId>
            <version>0.10.1</version>
        </dependency>
````
Also interesting that, when i try to run application form intellij idea, everything work fine, but after application is build, this error will appear.
 

## Environment info:

- RichTextFX Version: 0.10.1
- Operating System: Windows, Linux
- Java version: 11

**Comment by Jugen** [comment]
That's really strange because the version of TextFlowExt that uses TextFlowLayout is in the same package. So somehow it finds the one but the other is missing after the application is built ?

When IntelliJ builds your application does it extract or reassemble the library jars ?
Or is there a difference between the classpath IntelliJ uses and the one used with the build application ?

**Comment by kuzmenkoGift** [comment]
We build application using Maven and Spring Boot, and all we got about class path in our MANIFEST is 
````
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
````
All dependencies jars laying in "BOOT-INF/lib" folder. I found jar file with your library in it, and it\`s look exactly the same. Maybe class loader can`t find classes inside of META-INF directory?

**Comment by Jugen** [comment]
Something like that, except that it does find TextFlowExt inside of the META-INF folder but then somehow fails to find TextFlowLayout in the same place.

Unfortunately I don't have any experience with Spring Boot, so can't give any input there.

When you run your application from IntelliJ I assume it doesn't use Spring Boot but IntelliJ probably supplies a `-classpath` argument that includes all the libraries required and Java11 then correctly finds the classes in the META-INF versions folder.

Not sure if this is a good idea but maybe try putting the following in your application's MANIFEST and see if that works: `Class-Path: . BOOT-INF/lib/richtextfx-0.10.1.jar`

If it does then maybe there's a bug in the Spring Boot class loader ?

**Comment by kuzmenkoGift** [comment]
I just use debug, to check if it`s go to META-INF folder from Intellij. I find that you TextFlowExt class file not only in META-INF folder but in main directory too. That is why we can find TextFlowExt. But TextFlowLayout is only in META-Inf folder.

**Comment by Jugen** [comment]
No, there is supposed to be two (2) TextFlowExt class files. The one in the main directory is for Java 8 and the one under META-INF is for Java 9 and up. Only the Java 9 and up one uses TextFlowLayout. So I'm guessing that Spring Boot correctly loads TextFlowExt from META-INF (for Java 11) but then for some reason can't find TextFlowLayout ?

When you run your application from IntelliJ then Java 11 is able to correctly load both, or is it maybe using Java 8 ?

**Comment by kuzmenkoGift** [comment]
I check, and we using java 11.0.3. And i download source code for your library to better see what is going on. And, as you can see, program go to TextFlowExt what for java 8. 
![1](https://user-images.githubusercontent.com/28759843/61710538-86b23a80-ad5a-11e9-98ac-753dfbf349b0.png)

**Comment by Jugen** [comment]
Well that's not the right place in the code according to the stacktrace you gave above:

> java.lang.NoClassDefFoundError: org/fxmisc/richtext/TextFlowLayout
> 	at org.fxmisc.richtext.TextFlowExt.textLayout(TextFlowExt.java:29) ~[richtextfx-0.10.0.jar!/:0.10.0]
 
which is because IntelliJ is loading the source from the main directory as I don't think debuggers understand multi-release jar files. Note that a NoSuchMethodException is supposedly being thrown in your screen shot and not a NoClassDefFoundError as in the stacktrace.

Have you tried adding `Class-Path: . BOOT-INF/lib/richtextfx-0.10.0.jar` to your application's MANIFEST yet ?

**Comment by Jugen** [comment]
I just noticed that there is a difference between your Maven coordinates `<version>0.10.1</version>` and the stacktrace which reports `~[richtextfx-0.10.0.jar!/:0.10.0]` That is 10.1 versus 10.0 ?
If you have both jars on your classpath then maybe that's what the problem is.

**Comment by kuzmenkoGift** [comment]
I already tried to delete  previous versions of library from maven repository. Error still remains with both 0.10.0 and 0.10.1 versions. And, in built applications we have only one classpath and only one version of library. I am sorry for yours miss understanding, i just tried a lot of options will was waiting for response

**Comment by Jugen** [comment]
No problem :-)  What version of Spring Boot are you using ?
There was a Spring Boot issue: [Wrong entry may be loaded from multi-release jar files resulting in a NoClassDefFoundError](https://github.com/spring-projects/spring-boot/issues/15981) which was fixed in version **2.14**

**Comment by kuzmenkoGift** [comment]
I was using version 2.1.3. When I changed the version to a newer one, it worked) Thank you very much for your help.
